version: "2"

services:
  lowkey-vault:
    container_name: lowkey-vault-dotnet
    image: nagyesta/lowkey-vault:7.3.37@sha256:081c6be3b7ae8a3810ba7c414d47cc43529b29c9792387135a044a27d05d6ef0
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      LOWKEY_ARGS: "--server.port=8443 --app.token.port=8080"
