name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        module: [ core, framework ]
        include:
          - module: core
            name: .Net Core
            solution: dotnet-core/lowkey-vault-example-dotnet-core.sln
          - module: framework
            name: .Net Framework
            solution: dotnet-framework/lowkey-vault-example-dotnet.sln
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
      with:
        dotnet-version: 10.0.103
    - name: Setup NuGet
      uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2
      with:
        nuget-version: "7.0"
    - name: NuGet Restore ${{ matrix.name }} project
      run: nuget restore ${{ matrix.solution }}
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: temurin
        java-version: 25
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1
    - name: Download Lowkey Vault jar
      run: ./gradlew clean download
    - name: Build ${{ matrix.name }} Project
      run: dotnet build ${{ matrix.solution }} --no-restore
    - name: Test ${{ matrix.name }} Project
      run:  |
        java -jar lowkey.jar &
        Start-Sleep -s 10
        dotnet test ${{ matrix.solution }} --no-build --verbosity normal
        Stop-Job -Name "Job1"
